### ISSUE TITLE
Starting point of your application

### ISSUE THREAD

**Issue by pranayaryal** [mratsim/home-credit-default-risk#2]
Would you please point out the starting point of your application? Thanks.

**Comment by AdityaSoni19031997** [comment]
Run m100_predictions...
It took me more than 3 hours to figure that out!

**Comment by pranayaryal** [comment]
Thanks. Having a great readme with explanation of how to run the pipeline helps a lot like andrej has done here https://github.com/karpathy/arxiv-sanity-preserver

**Comment by mratsim** [comment]
Done, feel free to reopen if it's still not clear.
